server:
  port: 8080

spring:
  application:
    name: digital-banking-system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/banking_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Srushti@2022}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  sql:
    init:
      mode: always

# JWT Security Configurations
app:
  jwt:
    secret: 9a4f2c8d3e7b1a5f6c8d9e0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c
    expiration-ms: 86400000 # 24 hours

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.banking.system: DEBUG
